allowBuilds:
  "@prisma/engines": true
  '@sentry/cli': set this to true or false
  esbuild: true
  msgpackr-extract: set this to true or false
  prisma: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - "@rolldown/binding-darwin-x64@1.2.5"
  - "@rolldown/binding-linux-arm64-gnu@1.2.5"
